"""empty message

Revision ID: 19081cd31894
Revises: d73c9f4b151c
Create Date: 2017-05-08 16:20:54.982122

"""

# revision identifiers, used by Alembic.
revision = '19081cd31894'
down_revision = 'd73c9f4b151c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
