"""empty message

Revision ID: 560643af6b49
Revises: 
Create Date: 2017-05-28 19:43:07.246754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560643af6b49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paraphrase', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('paraphrase', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_paraphrase_created_at'), 'paraphrase', ['created_at'], unique=False)
    op.create_foreign_key(None, 'paraphrase', 'telegram_user', ['created_by'], ['id'])
    op.add_column('sentence_binary', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sentence_binary', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sentence_binary_created_at'), 'sentence_binary', ['created_at'], unique=False)
    op.create_foreign_key(None, 'sentence_binary', 'telegram_user', ['created_by'], ['id'])
    op.add_column('sentence_similarity', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sentence_similarity', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sentence_similarity_created_at'), 'sentence_similarity', ['created_at'], unique=False)
    op.create_foreign_key(None, 'sentence_similarity', 'telegram_user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sentence_similarity', type_='foreignkey')
    op.drop_index(op.f('ix_sentence_similarity_created_at'), table_name='sentence_similarity')
    op.drop_column('sentence_similarity', 'created_by')
    op.drop_column('sentence_similarity', 'created_at')
    op.drop_constraint(None, 'sentence_binary', type_='foreignkey')
    op.drop_index(op.f('ix_sentence_binary_created_at'), table_name='sentence_binary')
    op.drop_column('sentence_binary', 'created_by')
    op.drop_column('sentence_binary', 'created_at')
    op.drop_constraint(None, 'paraphrase', type_='foreignkey')
    op.drop_index(op.f('ix_paraphrase_created_at'), table_name='paraphrase')
    op.drop_column('paraphrase', 'created_by')
    op.drop_column('paraphrase', 'created_at')
    # ### end Alembic commands ###
